feat: Add settings overview for digital watchface
InfiniTimeOrg/InfiniTime pull request #1028
Opened 2022-03-10 22:59 UTC by Sykomaniac

### What does it do?
Create a settings overlay for the digital watchface to add colourful battery icon and battery percentage display. Implementation is similar to PineTime to avoid adding entries into main settings pages. Closes #582 

### Screenshots
![PXL_20220310_225147961 MP](https://user-images.githubusercontent.com/3231134/157769162-8e5c9a4f-e0f1-4bdf-832e-51c062a09f92.jpg)
![PXL_20220310_225156661](https://user-images.githubusercontent.com/3231134/157769178-674be8c9-763f-47a7-848a-077f174862d9.jpg)
![PXL_20220310_225207912](https://user-images.githubusercontent.com/3231134/157769183-f03688b9-5d1c-4561-9c94-1599b2e3f462.jpg)
![PXL_20220310_225213511](https://user-images.githubusercontent.com/3231134/157769189-22766cd4-c2d8-43f0-95fb-3c337252ec6c.jpg)

2022-03-12 10:38 UTC, kieranc commented
I'm very happy to see this implemented, it was on my to-do list!
The settings icon doesn't seem to be quite centered on the screen, is this intentional?
It feels like there are a lot of options which could be implemented but finding space for all the settings could be complicated. BG/text color, seconds display, date format etc. I wonder if the settings buttons which appears on long press could become 2 buttons, leading to 2 pages, one for color settings and one for other options?

2022-03-13 20:27 UTC, NeroBurner commented
works great with InfiniSim

![InfiniSim_2022-03-13_202335](https://user-images.githubusercontent.com/9076163/158077835-574ef20e-385e-4e5e-8dd2-55f22bff9bb3.png) ![InfiniSim_2022-03-13_202337](https://user-images.githubusercontent.com/9076163/158077837-aa292738-9afc-4e07-bc85-13a9bb5aac98.png) ![InfiniSim_2022-03-13_202340](https://user-images.githubusercontent.com/9076163/158077838-b59dd124-2b63-4df6-8804-a6db810ab4b8.png)
![InfiniSim_2022-03-13_202348](https://user-images.githubusercontent.com/9076163/158077839-73c47360-0b67-43c4-9f9c-f97754e46bcb.png) ![InfiniSim_2022-03-13_202352](https://user-images.githubusercontent.com/9076163/158077840-aa095472-012a-4b31-ad00-f423014168f2.png) ![InfiniSim_2022-03-13_202409](https://user-images.githubusercontent.com/9076163/158077841-52613ea7-e883-408e-ab50-cde37c78ee93.png)
![InfiniSim_2022-03-13_202421](https://user-images.githubusercontent.com/9076163/158077842-0506e535-2be3-4acc-bd4b-5596e19de9bb.png) ![InfiniSim_2022-03-13_202436](https://user-images.githubusercontent.com/9076163/158077843-0035451c-e473-4d3d-86e9-60c56ae48624.png)

2022-03-13 20:38 UTC, NeroBurner requested changes
you've changed Settings (i.e. you added new settings). You need to increment `settingsVersion`

```cpp
static constexpr uint32_t settingsVersion = 0x0003;
```

otherwise you are bound to run into the same errors as in PR https://github.com/InfiniTimeOrg/InfiniTime/pull/1024#issuecomment-1065530079

2022-03-13 20:38 UTC, NeroBurner commented on src/displayapp/screens/WatchFaceDigital.cpp
> +        lv_obj_set_style_local_text_color(batteryIcon, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, BatteryIcon::GetDefaultBatteryColor(batteryPercent));
here 2 extra spaces indentation slipped in.

2022-03-13 20:38 UTC, NeroBurner commented on src/displayapp/screens/WatchFaceDigital.cpp
> +        lv_obj_set_style_local_text_color(batteryIcon, LV_LABEL_PART_MAIN, LV_STATE_DEFAULT, BatteryIcon::GetBatteryColor(batteryPercent));
here 2 extra spaces indentation slipped in.

2022-03-16 12:01 UTC, Sykomaniac commented
@NeroBurner thanks for that I've incremented the settings version number
@kieranc no you are right that was an oversight and now corrected

2022-07-23 21:48 UTC, mashuptwice commented
As I've mentioned in #1205 , I don't quite see the necessity to add options about the battery feedback as quick settings. I cannot imagine anyone changing these settings very often, usually if someone prefers to have the battery percentage displayed in the status bar he will set it one time and keep it that way. 

Don't get me wrong, I am sure such quicksettings could be very useful for other options that someone would change multiple times a day.

I also very much like the idea of the colored battery icon!

2022-08-21 17:17 UTC, lman0 commented
any news @Sykomaniac ?

2022-08-21 18:53 UTC, Sykomaniac commented
Happy to update the PR to the latest code base if desired

2024-01-30 18:05 UTC, closed without merging