Update arm gcc toolchain to 11.2-2022.02
InfiniTimeOrg/InfiniTime pull request #1124
Opened 2022-05-10 18:29 UTC by FintasticMan

Updates the buildAndProgram doc and the docker image, but not GitHub Actions.

Once GH Actions use Docker to build the firmware, that should be fine.

2022-05-23 13:03 UTC, Tiggilyboo commented
Works well for me, cheers!

2022-06-05 07:05 UTC, Riksu9000 reviewed
The old compiler version is still referenced in some places and should probably be updated.

2022-06-05 11:13 UTC, FintasticMan commented
I've just replaced the rest of the references to the old gcc version, except for in the vscode devcontainer because that needs a lot more changes to make it work with the current code. I do think that @geekbozu is working on making it work with the main docker image.

2022-06-05 22:13 UTC, geekbozu commented
I am and I'm making it use the main docker file/image so this helps me as well! It's almost done I'm just having some line ending issues that I'm blaming on windows :p

2022-06-06 15:42 UTC, NeroBurner requested changes

2022-06-06 15:42 UTC, NeroBurner commented on doc/buildAndProgram.md
> + - A cross-compiler : [ARM-GCC (11.2-2022.02)](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads)
I think it should be more explicit here that we need a compiler with the arm 32bit eabi target. Maybe add the explicit link for linux amd64 host

```suggestion
 - A cross-compiler : [ARM-GCC eabi (11.2-2022.02)](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/downloads)
   - For an amd64 linux host [gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz](https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi.tar.xz)
```

2022-06-06 16:40 UTC, NeroBurner approved these changes

2022-06-06 18:44 UTC, JF002 commented
@FintasticMan Thanks for this PR! Upgrading to an up-to-date version of the compiler is certainly a good thing!
Have you done some tests on builds built by the new version of GCC to confirm that it's working correctly?

2022-06-06 19:12 UTC, NeroBurner commented
I've just flashed a build using the mentioned gcc 11 compiler on my pinetime. Everything seems to be fine. What I've tested so far:
- I can play pong
- I can play Twos
- Accellerometer values are shown
- Stopwatch, Alarm and Timer work
- Pinetime Watchface is showing the time and the current bluetooth connection
- Firmware can be validated
- Brightness can be changed in QuickSettings
- The Torch app shines bright

I haven't checked notifications

2022-06-06 19:23 UTC, FintasticMan commented
All of my builds for testing features etc. for the past couple of months have all been built with this new compiler version and I haven't noticed any issues or had any crashes. I haven't done any rigorous testing however. To add to the comment above, I have definitely recieved notifications during this time.

2022-06-06 19:26 UTC, JF002 commented
@FintasticMan 

> All of my builds for testing features etc. for the past couple of months have all been built with this new compiler version and I haven't noticed any issues or had any crashes. I haven't done any rigorous testing however. To add to the comment above, I have definitely recieved notifications during this time.

Great, thanks for this confirmation!

2022-06-11 19:59 UTC, Riksu9000 approved these changes

2022-06-11 19:59 UTC, merged