Automatically create enough screens for all apps and settings
InfiniTimeOrg/InfiniTime pull request #1153
Opened 2022-05-20 09:13 UTC by Riksu9000

Apps and settings are now stored in a single array. Adding more entries will automatically create more screens.

I'm assuming there's a reason for std::function, because I don't know exactly what it does.

2022-06-06 18:17 UTC, JF002 commented
This is a great use for `constexpr` :+1:

2022-06-06 18:17 UTC, JF002 approved these changes

2022-06-16 15:37 UTC, NeroBurner requested changes

2022-06-16 15:37 UTC, NeroBurner commented on src/displayapp/screens/settings/Settings.cpp
> +#include "displayapp/Apps.h"
please move before `DisplayApp.h` include for alphabetical ordering

2022-06-16 15:37 UTC, NeroBurner commented on src/displayapp/screens/ApplicationList.h
> +        static constexpr std::array<Tile::Applications, appsPerScreen * 2> applications {{
`nScreens` is explicitly mentioned here as 2. If I want to add another app to the list I need to add the `2` to `3`, which is equivalent to `nScreens`.

We could explicilty set `nScreens` and then calculate the `applications.size()` instead

If I just add an `+1` to add the new application as the only app on the third screen then I get an error at runtime when I swipe to the third screen

2022-06-16 15:37 UTC, NeroBurner commented on src/displayapp/screens/settings/Settings.h
> +        static constexpr std::array<List::Applications, entriesPerScreen * 4> entries {{
same as above, `nScreens` is already mentioned to be 4

2022-06-16 19:04 UTC, NeroBurner requested changes

2022-06-16 19:04 UTC, NeroBurner commented on src/displayapp/screens/ApplicationList.cpp
>  #include <array>
`std::function` and `std::unique_ptr` are used in this file. We should include the corresponding headers [<functional>](https://en.cppreference.com/w/cpp/header/functional) and [<memory>](https://en.cppreference.com/w/cpp/header/memory)

```suggestion
#include <array>
#include <functional>
#include <memory>
```

2022-06-16 19:04 UTC, NeroBurner commented on src/displayapp/screens/settings/Settings.cpp
>  #include <array>
`std::function` and `std::unique_ptr` are used in this file. We should include the corresponding headers [<functional>](https://en.cppreference.com/w/cpp/header/functional) and [<memory>](https://en.cppreference.com/w/cpp/header/memory)

```suggestion
#include <array>
#include <functional>
#include <memory>
```

2022-06-16 19:29 UTC, NeroBurner approved these changes
LGTM

2022-06-16 19:41 UTC, merged