Fix various typos
InfiniTimeOrg/InfiniTime pull request #1164
Opened 2022-05-31 19:20 UTC by luzpaz

Found via `codespell -q 3 -S ./src/libs -L ans,doubleclick,trough`

2022-06-01 06:46 UTC, FintasticMan requested changes
Almost everything is good, just one false positive.

2022-06-01 06:46 UTC, FintasticMan commented on doc/ble.md
> +When the connection is established, the PineTime will try to discover services running on the companion application. For now **CTS** (**C**urrent **T**ime **S**ervice) and **ANS** (**A**lert **N**not
This is not a typo

2022-06-02 06:44 UTC, Riksu9000 approved these changes
The code formatting check can be ignored.

2022-06-02 19:01 UTC, NeroBurner approved these changes

2022-06-05 06:31 UTC, merged