Flashlight default to max brightness
InfiniTimeOrg/InfiniTime pull request #1181
Opened 2022-06-13 20:58 UTC by Riksu9000

Includes tiny code tweaks.

~~Depends on #1180~~

Fixes #836

2022-06-16 15:00 UTC, NeroBurner requested changes

2022-06-18 17:24 UTC, NeroBurner approved these changes

2022-06-19 13:51 UTC, Avamander approved these changes

2022-06-19 16:24 UTC, JF002 approved these changes

2022-06-19 16:24 UTC, merged

2022-06-26 01:27 UTC, Danimations commented
Great move... looking forward to this small but significant improvement!