Add pink color
InfiniTimeOrg/InfiniTime pull request #1325
Opened 2022-09-12 08:25 UTC by Akselmo

Let's try this again. This was previously attempted at https://github.com/InfiniTimeOrg/InfiniTime/pull/1300

I had some trouble with accidentally modifying the *submodules* instead of the InfiniTime project itself, so the tests kept failing.
Oh well, live an learn!

![image](https://user-images.githubusercontent.com/13801236/189606704-638abfe6-6eab-4ece-afc3-e1d39d666cf6.png)

Anyhow, here it is, a pretty pink color!

As per the previous PR:

My fiancee was absolutely devastated there was no proper pink color in the device, so I wanted to add it.

Apparently this is the true pink color. :smile: 

She was happy with it, I hope you are too. :smile:

2022-09-13 16:47 UTC, NeroBurner requested changes
Other than the removed trailing newlines looking good :purple_heart:

2022-09-13 16:47 UTC, NeroBurner commented on src/components/settings/Settings.h
> +}
Please don't remove the last empty line at the end of the files. Try to keep the commits clean.

```suggestion
}

```

2022-09-13 16:47 UTC, NeroBurner commented on src/displayapp/Colors.cpp
> +}
Please don't remove the last empty line at the end of the files. Try to keep the commits clean.

```suggestion
}

```

2022-09-13 16:47 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePineTimeStyle.cpp
> +}
Please don't remove the last empty line at the end of the files. Try to keep the commits clean.

```suggestion
}

```

2022-09-13 20:36 UTC, NeroBurner approved these changes
LGTM

2022-09-17 19:32 UTC, merged

2022-09-17 19:32 UTC, JF002 commented
@Akselmo Thank you for your first contribution in InfiniTime :+1: and sorry for the time it took to review it. I hope your fiancee is still happy with her PineTime!

2022-09-17 19:35 UTC, Akselmo commented
> @Akselmo Thank you for your first contribution in InfiniTime +1 and sorry for the time it took to review it. I hope your fiancee is still happy with her PineTime!

Thanks and no problem. She likes it even better now with the pink color! :smile: