added temperature to digital watch face
InfiniTimeOrg/InfiniTime pull request #1329
Opened 2022-09-14 17:36 UTC by minacode

This PR is a test-implementation for #1327 .
I added the temperature value from the driver to the digital watch face.
And the value is: (drum roll...) 1. Always.

If someone sees something I did not see to make this useful, please send help!

I am adding this here as a Draft, because it might be of interest for some people, but is obviously not something we want to merge.

2022-09-15 00:36 UTC, ght commented
Thanks for investigating! I was wondering about this too since finding out about it in the datasheet. Kinda disappointing that it does not seem to work.

2022-09-15 07:48 UTC, minacode commented
[Here](https://github.com/BoschSensortec/BMA423-Sensor-API/blob/master/examples/generic/temperature/temperature.c) is an example that might be useful.

2022-09-16 21:15 UTC, ght requested changes
I just tested this branch and it actually works fine if you fix the type!

2022-09-16 21:15 UTC, ght commented on src/displayapp/screens/WatchFaceDigital.h
> +        DirtyValue<bool> temperature {};
```suggestion
        DirtyValue<uint32_t> temperature {};
```

2022-09-16 21:16 UTC, minacode commented
Good catch, thank you!

2022-09-16 21:38 UTC, minacode commented
Now its always 32000. Do you have useful values?

2022-09-16 21:40 UTC, ght commented
Yes, but it changes very slowly. Try leaving it in the fridge for 5 minutes.

2022-09-17 17:36 UTC, minacode commented
So I am getting values between 25 and 32 (times 1000). They match the surroundings a little bit, but they change very slowly. 
But I don't think that they are sensitive enough for a temperature app. I will continue the measurements for a while though.

2022-10-20 17:17 UTC, minacode commented
I am closing this one because I sadly don't see any future for this.

2022-10-20 17:17 UTC, closed without merging