Proper battery percentage
InfiniTimeOrg/InfiniTime pull request #1398
Opened 2022-10-29 00:10 UTC by AlexXZero

This PR adds linear approximation util and use it for making battery discharge curve more linear.

These changes were done independently on https://github.com/InfiniTimeOrg/InfiniTime/pull/585, I guess my solution is more generic. The main idea of my PR is adding linear approximation which might be used in any other feature including this old PR.
I used my own measurements of battery, not sure if they accurate enough, so you are welcome to update my digits:
```C
  static const Utility::LinearApproximation<uint16_t, uint8_t, 5> aprox {{{
    {3200, 0},  // minimum voltage of battery before shutdown ( depends on the battery )
    {3600, 10}, // keen point corresponded to 10% of battery
    {3700, 25},
    {3800, 50},
    {4180, 100} // maximum voltage of battery ( max charging voltage is 4.21 )
  }}};
``` 
My measurements:

![image](https://user-images.githubusercontent.com/3096462/198750327-c3409136-aef2-4b10-863f-e6033affb23b.png)
blue - measured voltage
red - measured percentage (using 1.9.0)
orange - filtered voltage (I'm working on adding filter in another branch)
green - expected percentage using this algorithm (actually data is filtered, but it shows trade line of approximation)

I can share my data by request.

2022-10-29 09:23 UTC, minacode commented
I will cut out the hacky rescaling in my low battery warning PR for this. This looks good.

2022-11-01 06:37 UTC, AlexXZero commented
I updated approximation points to get better results:
![image](https://user-images.githubusercontent.com/3096462/199173244-63bd176d-a231-49b2-83e0-772749a7a96a.png)

blue - measured voltage
orange - filtered voltage (filtering will be implemented as another feature)
green - percentage using old algorithm
black dashed - ideal percentage
red - percentage using approximation (current PR version)
purple - percentage using approximation + filtering (future version)

2022-11-01 08:26 UTC, FintasticMan commented
Looks good! I quite like that #585 changes the minimum voltage to 3.5v, which makes it easier to remember to charge the watch on time. Maybe that could be done here as well?

2022-11-01 09:12 UTC, AlexXZero commented
Changed minimum voltage to 3.5V (now red and purple drop down to 0% when voltage is 3.5V)
![image](https://user-images.githubusercontent.com/3096462/199199736-910139f0-7396-45c4-bbda-864a9df24058.png)

2022-11-03 19:15 UTC, AlexXZero commented
@JF002 I think this PR is ready to be merged into develop. Let me know if I need to run some extra tests before it. I have tested these changes on my dev kit and on a sealed during a few weeks and everything looks good.
Here is diagram which only shows how battery percentage was dropped before (green line) and after (red line). It also shows measured voltage (blue line) and ideal percentage line.

![image](https://user-images.githubusercontent.com/3096462/199813062-be1e363c-4739-422d-9969-8c5e82a8b6d3.png)
In my last commit I fixed code style to pass github pipeline, but I don't have permissions to ruin it.

2022-11-06 20:03 UTC, NeroBurner requested changes

2022-11-06 20:03 UTC, NeroBurner commented on src/components/battery/BatteryController.cpp
> +      newPercent = std::min(aprox.GetValue(voltage), (isCharging ? uint8_t {99} : uint8_t {100}));
little nitpick, the `()` on the `isCharging` ternary if operator isn't needed

```suggestion
      newPercent = std::min(aprox.GetValue(voltage), isCharging ? uint8_t {99} : uint8_t {100});
```

2022-11-07 10:33 UTC, NeroBurner approved these changes
looking forward to charge my pinetime at 10% instead of at 40% :smiley:

2022-11-10 20:53 UTC, alexdolzhenkovbdl commented
@JF002 It looks like I don't have permissions for merging it. But I believe it is ready for that. Could you provide any steps I need to do next or just merge the PR if you agree with what was done.

2022-11-10 20:55 UTC, AlexXZero commented
> @JF002 It looks like I don't have permissions for merging it. But I believe it is ready for that. Could you provide any steps I need to do next or just merge the PR if you agree with what was done.

Oh, it looks like I wrote my message with working account. So it was me :-)

2022-11-14 20:18 UTC, JF002 commented
> It looks like I don't have permissions for merging it. 

Only me and the member of the @InfiniTimeOrg/core-developers team have write access to the repo :)

> But I believe it is ready for that. Could you provide any steps I need to do next or just merge the PR if you agree with what was done.

Thanks for your contribution! The next step is to wait for us to review the PR, which can take some time (there are **a lot** of PRs in the backlog, as you can see).

There's already another PR that does more of less the same things : https://github.com/InfiniTimeOrg/InfiniTime/pull/585. How does it compare to this one?

2022-11-15 06:20 UTC, AlexXZero commented
Thank you for your feedback. I saw this PR and agree that it seems to do the same thing. But I found their implementation too complex and more hardcoded to be used only for battery percentage. Also comparing with #585 it doesn't use float pointer numbers, so it should work quicker and take less memory/CPU resources. My changes adds class for approximation any data and anyone can reuse it for something else.

Actually I would appreciate merging any of this two PRs, as both of them improve user experience in terms of showing proper battery percentage.

2022-11-15 13:39 UTC, FintasticMan commented
I'm currently collecting battery data from all 3 of my PineTimes, so that the data from multiple batteries can be combined. This should give slightly more accurate results.

2022-11-15 20:25 UTC, SteveAmor commented
When complete, it would be good to update the bootloader with the same algorithm 😀 At the moment, the bootloader (V1.0.0) battery voltage reads higher than the V1.11.0 voltage.

2022-11-19 09:23 UTC, JF002 commented
> Actually I would appreciate merging any of this two PRs
I think this is what I'll eventually do :)

> as both of them improve user experience in terms of showing proper battery percentage.
Agreed!

2022-11-19 15:36 UTC, JF002 commented
We merged this PR in #1444.
Thanks a lot for your work, @AlexXZero !

2022-11-19 15:36 UTC, closed without merging