Small Chimes fix
InfiniTimeOrg/InfiniTime pull request #1402
Opened 2022-10-30 04:11 UTC by Elements6007

Fixes the missing "s" at the end of "mins" in the Chimes settings. 
![InkedPXL_20221030_035021069small](https://user-images.githubusercontent.com/88860704/198861886-368d41bb-7fd9-4d98-84f4-e0284e2f09e5.jpg)

^"s" is cut off

![PXL_20221030_033625363small](https://user-images.githubusercontent.com/88860704/198861872-84269966-7459-4b42-a68d-ecc4da1501d8.jpg)

^"s" is now fully visible

2022-10-30 08:50 UTC, JF002 reviewed
Looks good to me, thanks! 

Would you like to have a look and check why the code formatting workflow failed during the build?

2022-10-30 12:55 UTC, Elements6007 commented
> Looks good to me, thanks!
> 
> Would you like to have a look and check why the code formatting workflow failed during the build?

I forgot to run the Clang format because it was just a small edit, it should be fixed now. Thanks!

2022-11-06 19:22 UTC, NeroBurner requested changes

2022-11-06 19:22 UTC, NeroBurner commented on src/displayapp/screens/settings/SettingChimes.h
> +}
Does the clang format actually require no newline at the end of the file? I don't think so, could you please check and revert

```suggestion
}

```

2022-11-06 20:52 UTC, NeroBurner approved these changes
Looking good now, thanks for the fix!

![InfiniSim_2022-11-06_205140](https://user-images.githubusercontent.com/9076163/200194547-7a091640-ba2b-474d-99d3-d009094c509c.png)

2022-11-19 09:38 UTC, JF002 approved these changes

2022-11-19 09:38 UTC, JF002 commented
Thanks !

2022-11-19 09:39 UTC, merged