DateTimeController: Use std::tm for storing date
InfiniTimeOrg/InfiniTime pull request #1634
Opened 2023-02-23 17:22 UTC by Riksu9000

2023-02-23 20:03 UTC, NeroBurner requested changes
small nitpick because of include, but other than that looking good. Thanks for teaching me the existence of `std::tm` from the `C` world. I only knew about the `std::chrono` and `date` library for datetimes

2023-02-23 20:03 UTC, NeroBurner commented on src/components/datetime/DateTimeController.h
> +      std::tm localTime;
missing include for `std::tm`, please add `#include<ctime>` at the top

2023-02-23 21:11 UTC, NeroBurner approved these changes

2023-02-25 15:31 UTC, JF002 commented
> Thanks for teaching me the existence of std::tm from the C world.

Same for me :)

2023-02-25 15:32 UTC, JF002 approved these changes

2023-02-25 15:37 UTC, merged