WatchFaceG7710: Simplify time update check
InfiniTimeOrg/InfiniTime pull request #1665
Opened 2023-03-03 11:15 UTC by Riksu9000

2023-03-14 20:43 UTC, FintasticMan requested changes
Except for the uses of auto, this looks good to me.

2023-03-14 20:43 UTC, FintasticMan commented on src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
>      auto minute = dateTimeController.Minutes();
Don't use auto for integers.

2023-03-14 20:43 UTC, FintasticMan commented on src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
> +      auto dayOfYear = dateTimeController.DayOfYear();
Don't use auto for the integers here.

2023-03-14 20:46 UTC, FintasticMan commented on src/displayapp/screens/WatchFaceCasioStyleG7710.cpp
> +      auto weekNumberFormat = "%V";
It's better to not use auto for arrays IMO, it just makes it confusing.

2023-04-02 14:29 UTC, JF002 approved these changes

2023-04-02 18:14 UTC, merged