WatchFaceTerminal: Simplify time update check
InfiniTimeOrg/InfiniTime pull request #1666
Opened 2023-03-03 11:20 UTC by Riksu9000

2023-03-14 20:49 UTC, FintasticMan requested changes
Looks good.

2023-03-14 20:49 UTC, FintasticMan commented on src/displayapp/screens/WatchFaceTerminal.cpp
>      auto second = dateTimeController.Seconds();
Don't use auto for integers.

2023-03-14 20:49 UTC, FintasticMan commented on src/displayapp/screens/WatchFaceTerminal.cpp
> +      auto day = dateTimeController.Day();
Don't use auto for the integers here.

2023-04-02 14:29 UTC, JF002 approved these changes

2023-04-02 18:19 UTC, merged