Update Apps.md
InfiniTimeOrg/InfiniTime pull request #1752
Opened 2023-04-27 22:38 UTC by Alex-EEE

Example code will not compile.  Screen no longer takes an arg

2023-08-11 09:54 UTC, FintasticMan requested changes
We should keep the docs updated.

2023-08-11 09:54 UTC, FintasticMan commented on doc/code/Apps.md
> +MyApp::MyApp() : Screen() {
The constructor doesn't need to init a Screen instance.

```suggestion
MyApp::MyApp() {
```

2023-09-16 08:09 UTC, FintasticMan approved these changes

2023-11-16 17:30 UTC, kieranc approved these changes
Looks good :+1:

2023-11-16 17:46 UTC, merged