Typo fixed
InfiniTimeOrg/InfiniTime pull request #1915
Opened 2023-11-19 23:11 UTC by everypizza1

2023-11-28 21:14 UTC, FintasticMan requested changes

2023-11-28 21:14 UTC, FintasticMan commented on README.md
> +I’m not working alone on this project. First, many people create pull requests for this project. Then, there is the whole #pinetime community: a lot of people all around the world who are hacking, se
I think it makes more sense to keep the "the" here.

2023-11-28 22:27 UTC, FintasticMan approved these changes

2023-12-23 20:45 UTC, JF002 approved these changes

2023-12-23 20:45 UTC, JF002 commented
Thanks and congrats on your first contribution to InfiniTime!

2023-12-23 20:45 UTC, merged

2023-12-23 20:46 UTC, everypizza1 commented
You're welcome! 🤗


________________________________
From: JF ***@***.***>
Sent: Saturday, December 23, 2023 2:45:57 PM
To: InfiniTimeOrg/InfiniTime ***@***.***>
Cc: Derry Tutt ***@***.***>; Author ***@***.***>
Subject: Re: [InfiniTimeOrg/InfiniTime] Fix typos/improve grammar (PR #1915)


Thanks and congrats on your first contribution to InfiniTime!

—
Reply to this email directly, view it on GitHub<https://github.com/InfiniTimeOrg/InfiniTime/pull/1915#issuecomment-1868367449>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATXE5QKUTLS52HI3ATG7MYDYK47ILAVCNFSM6AAAAAA7SCBFBCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRYGM3DONBUHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>