Trans watchface
InfiniTimeOrg/InfiniTime pull request #2201
Opened 2024-12-16 17:34 UTC by Aperture32GLaDOS

Adds a new watch face with the trans flag as a background
# Features
* A new watch face, featuring the trans flag
* Bluetooth indicator in the top right
* Long day names
# Images
![image](https://github.com/user-attachments/assets/037b1006-cd39-49f6-a3da-c5e65a5b8b78)

2024-12-30 14:56 UTC, marigoldfish commented
Love it! 🏳️‍⚧️😁 You are a very cool person, I'm going to be using this for a while!

![IMG_20241229_213604426~2](https://github.com/user-attachments/assets/d4bd6594-def1-4118-a460-417aec116809)

2024-12-30 18:09 UTC, mark9064 reviewed
Thanks for the contribution :)

2024-12-30 18:09 UTC, mark9064 commented on src/displayapp/screens/WatchFaceTrans.h
> +        Utility::DirtyValue<int> batteryPercentRemaining {};
`uint8_t` is sufficient here

2024-12-30 18:49 UTC, Aperture32GLaDOS commented
Thanks for the quick feedback! I've implemented those changes, hopefully everything's good now

2025-01-03 23:05 UTC, mark9064 commented
All looks good to me! You couldn't have made review easier :)

I haven't had the chance to test on hardware yet and am away for now, but I should be able to test within a couple weeks time

2025-01-04 06:07 UTC, marigoldfish commented
I have been using this daily, and I really like it, but I have a few small suggestions:

I adore the "You have mail." for notifications, but I dislike that it overlaps so severely with the battery percentage:

![IMG_20241231_082654043~2](https://github.com/user-attachments/assets/a1ce6a95-e0c9-475a-8f00-78566dc49af4)

I think it might look better to have "mail." on its own line below, and move "You have" up a little bit so they're both centered vertically in the blue stripe. 

(The 90's kid in me really wants it to read "You've got mail," like AOL, but that's not a request for a change, just a nostalgic observation)

My other suggestion is to name the watch face more specifically as "Trans Flag" instead of just "Trans."

![IMG_20250103_220544316_HDR~2](https://github.com/user-attachments/assets/9134d229-ab31-4878-90d1-a475722dc3a2)

Like I said, very very small suggestions. The other 99% of this watchface is grand!

2025-01-04 11:45 UTC, Aperture32GLaDOS commented
I definitely agree with the notification and the name. Fortunately, these are just one-line fixes so it's not that hard to change.
![image](https://github.com/user-attachments/assets/730ed8c2-4934-47b7-b486-229ce140df88)

2025-01-04 15:57 UTC, marigoldfish reviewed
If I can nitpick, I think "Mail" should be lowercase. But this looks really good 😁

2025-01-04 16:09 UTC, Aperture32GLaDOS commented
Good spot, I'll fix that

2025-01-04 16:14 UTC, marigoldfish commented
You are an incredibly awesome and speedy person! Thanks for implementing my suggestions, and so fast! I'll keep testing this daily for a while and let you know if I come across anything else 😁

2025-01-18 02:56 UTC, marigoldfish commented
Hello again, I noticed another little thing after using this watch face for a while. 

Usually I keep my watch in 24 hour time, but I had reason to use 12 hour time today, and I noticed that both AM and PM show up as "M."

(I manually set the watch to 2am to get the second picture, I didn't stay up late 😜)

![IMG_20250117_184147295~2](https://github.com/user-attachments/assets/a715da1a-3dd0-46cb-9a6b-6025be84870d)
![IMG_20250117_184236513~3](https://github.com/user-attachments/assets/39e872c3-51fa-49dc-8feb-f1ca364f8b8a)

2025-01-18 11:48 UTC, Aperture32GLaDOS commented
I think what's happening here is that the font used for the time doesn't have all the alphabet, if I change the font to something else it seems to work fine:
![image](https://github.com/user-attachments/assets/c4f4d4c7-9e04-43ba-8d2c-2f328641920e)
I've moved the AM/PM display to the day, since that uses a font which has all the alphabet
![image](https://github.com/user-attachments/assets/ae02b2df-8cb6-4201-af1d-009e858799e3)

2025-01-20 04:38 UTC, marigoldfish commented
That's an elegant fix! I like it! 

Unfortunately, in addition to praise I also come bearing news of a new bug: it is displaying 24-hour time when I have 12-hour time enabled.

![IMG_20250119_203002810~2](https://github.com/user-attachments/assets/1be60a2a-995b-47a9-ae21-5afe0198338b)

2025-01-20 14:10 UTC, Aperture32GLaDOS commented
Aah, well at least that's an easy fix; it *should* all be working now
![image](https://github.com/user-attachments/assets/f4b76fdc-7f45-415c-a95c-bfaabc8a712d)

2025-02-02 21:40 UTC, NeroBurner commented
could you update to/rebase onto the latest `main` branch. The toolchain won't run as the `artifacts v3` job was deprecated by GitHub, and that is fixen in the current `main` branch

2025-02-10 06:19 UTC, rdub1a4 commented
Seems like this would wait for side loading. It may not fit the vision of "Only a minimal feature set in the flashed firmware".  But, no biggy.

2025-02-10 18:35 UTC, mark9064 commented
Because it doesn't depend on any other PRs and was easy to review mainly

Things get added to the milestone when we want to target including them this cycle. If a PR prevents on lots of other refactoring for example, or has outstanding bugs that are taking time to resolve, then it usually won't be queued up for the next cycle until it's ready. InfiniTime generally lacks reviewers though, so what gets queued and what doesn't depends on whether someone's had time to look at it properly though

2025-02-14 22:22 UTC, mark9064 approved these changes
All LGTM code wise :)
Could you rename the watch face class/code/enum entry to (WatchFace)TransFlag? I think it makes sense for the code to match the displayed name

Haven't tested on HW yet

2025-02-15 13:19 UTC, Aperture32GLaDOS commented
Yeah, that makes sense - I've renamed all the WatchFaceTrans to WatchFaceTransFlag

2025-03-23 05:17 UTC, joseph58tech commented
Wait why don't we use this as a general LGBTQ flag watchface? It would make the most sense to add all of the flags into the design if we already have the one. You can choose which one you want the same way you change the colors on the Infinineat watchface.

2025-03-23 12:18 UTC, Aperture32GLaDOS commented
I really like that idea! I've implemented four pride flags, (the classic rainbow, the existing trans flag design, the bi flag and the lesbian flag), and the switching seems to work fine

2025-03-23 12:19 UTC, Aperture32GLaDOS commented
![image](https://github.com/user-attachments/assets/768b58a0-0086-465d-8dc7-e33b5dbc5bb3)
![image](https://github.com/user-attachments/assets/8e7d0c33-c895-4172-b499-384c68ea5d76)
![image](https://github.com/user-attachments/assets/a9efde89-81f5-4d5c-a741-be4b7889326f)
![image](https://github.com/user-attachments/assets/426adabc-43b1-4eca-a7fe-5698b146d6ba)

2025-03-23 15:23 UTC, Aperture32GLaDOS commented
Oops

2025-05-16 03:22 UTC, marigoldfish commented
I have been using these new flag watchfaces for a while and have gotten several compliments from queer colleagues! I don't know if I have successfully convinced anyone to buy a Pinetime, but multiple people thought it was cool and wanted me to pass along their compliments. :rainbow_flag: 

I do have some minor readability feedback after test driving these for a month. As usual for my feedback they are EXTREMELY minor, and mostly come down to my taste, so take 'em or leave 'em as you wish :stuck_out_tongue: 

- I feel like the bi flag would have better contrast if the time was white and the date/steps/battery were black.

- I use the rainbow face the least, because the time is the least legible to me. I know this would make it inconsistent with the other faces, but  it would be easier to see if the time were centered on the yellow stripe.

- The time seems off-center vertically by a couple pixels or so. I wouldn't normally be nitpicky about something so small, but it's noticeable in the lesbian flag. Because the middle stripe is so narrow, the time aligns with the bottom but not the top.

2025-05-16 13:02 UTC, Aperture32GLaDOS commented
Thanks for the feedback! I definitely agree with your points - I've changed the time label's positioning (it's still not exactly center - it's an off by about half a pixel, but it's not really visibly wrong, even on the lesbian flag), and I've made it so that the bi flag has switched black and white text parts. I tried your suggestion with the rainbow flag, but I feel like what you gain in readability is lost in the formatting - I also tried using different colours for the time, but that didn't really help either.
![image](https://github.com/user-attachments/assets/87d9a33a-ff48-4979-9f65-2210dc50b4fe)
![image](https://github.com/user-attachments/assets/f604fd13-638e-4ea3-b36b-d12333bbaa4d)
![image](https://github.com/user-attachments/assets/cebd2ec8-cf9f-4f41-bb74-f78fe1d2915a)

2025-06-04 15:40 UTC, mark9064 commented
When this is ready for review let me know ^^
All faces look finished to me visually other than the rainbow flag, the difference in lightness between the yellow and green definitely makes it hard... not sure I have any useful suggestions there
Also, it'd be worth checking how the watchfaces look with AOD, if they looks odd it might be worth tweaking some colours a little to make the AOD presentation nicer

2025-06-04 18:12 UTC, marigoldfish commented
I have continued to "field test" these faces and I don't have any more feedback on appearance or alignment or whatnot. 👍🏻 

I personally like the rainbow flag having the time entered on the yellow stripe, but I am willing to defer on matters of opinion. I have a rainbow watch strap so I'm more likely to use the trans or lesbian flag anyway.

That's a good point re AOD - I took a quick look while I was on the bus and they are quite different with it enabled (and I discovered a potential-bug in AOD that I'm going to investigate and write up separately if I can reproduce it). They show the time legibly, but the pride flags lose some of their distinction.

2025-06-16 10:53 UTC, Aperture32GLaDOS commented
I think for now it's easier to just remove the rainbow version - maybe in future I can figure out a way of making it look good. For now, I've replaced it with the mlm flag (it was also bugging me, I think if we have the wlw one we've gotta have the mlm one as well).
![image](https://github.com/user-attachments/assets/60118fbf-a3d0-4f65-9891-b781b10a3917)

2025-06-16 13:33 UTC, mark9064 commented
Sure, removing it for now until a better design is settled on makes sense.

For the mlm flag, should the text other than the time be white? Especially at the bottom the contrast looks quite poor

2025-06-16 13:37 UTC, Aperture32GLaDOS commented
![image](https://github.com/user-attachments/assets/a020f967-6ebb-4270-abd3-5474f4d245a8)
I think I'm gonna have to have the text on top be black and the text on bottom be white

2025-06-16 14:36 UTC, Aperture32GLaDOS commented
![image](https://github.com/user-attachments/assets/497501b1-13e0-4a91-b193-0bad80e7941b)
Yeah, that works quite well I think

2025-06-16 18:32 UTC, NeroBurner commented
Plesse increase the `settingsVersion` number. we do this everytime a new setting is added

2025-06-16 19:07 UTC, NeroBurner requested changes

2025-06-16 19:07 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +#include <displayapp/Controllers.h>
please use "" for this incluse. controllers.h is one of our headers

2025-06-16 19:07 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        char defaultTopLabelColour[8] = "#ffffff";
can we move the colors and default values from the header to a private namespace in the CPP file? I'd like to keep the header as clean and minimal as possible

2025-06-16 19:07 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +#include "components/ble/BleController.h"
nitpick: I think it is possible to remove the includes for ble and other components as we forward declare them. please try :)

2025-06-16 19:07 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +#include "displayapp/screens/WatchFacePrideFlag.h"
please make the watchface header the first include, just feels better to have the corresponding header first

2025-06-16 19:07 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        lv_obj_t** backgroundSections;
I don't like manual memory management. It's much too error prone to create a memory leak. please replace with a std::vector or similar

2025-06-16 19:58 UTC, Aperture32GLaDOS commented
Yup, all makes sense. I've implemented the suggested changes, and it still compiles and works

2025-06-16 20:03 UTC, Aperture32GLaDOS commented
Oof, I'll sort that out in a bit

2025-06-16 20:50 UTC, NeroBurner requested changes
coming along nicely. Some code duplication I'd like to get rid of remains

2025-06-16 20:50 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  static constexpr lv_color_t steelBlue = LV_COLOR_MAKE(0x3d, 0x1a, 0x78);
we're now in a namespace, you can drop the `static` here :)

2025-06-16 20:50 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    lv_obj_del(backgroundSections[i]);
with the use of `std::vector` we can now get rid of the indexed access and switch to a for-each loop (please check my syntax, didn't compile it :sweat_smile: )


```suggestion
  for (auto backgroundSection: backgroundSections) {
    lv_obj_del(backgroundSections[i]);
```

2025-06-16 20:50 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
>          lv_obj_set_size(backgroundSections[i], LV_HOR_RES, (LV_VER_RES / numBackgrounds) + 1);
the background sections creation has much code duplication. Can we maybe restructure it in a way such that we have a data structure with the colors per case stored as constexpr and use `std::transform` to create the background sections from it

2025-06-16 20:51 UTC, NeroBurner commented
totally optional: could you update the initial PR description to contain updated images for the currently implemented pride flags?

2025-06-16 21:00 UTC, mark9064 reviewed
Looking good! Sounds like my thoughts are pretty similar to @NeroBurner regarding duplication

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if ((event == Pinetime::Applications::TouchEvents::DoubleTap) && (lv_obj_get_hidden(btnClose) == false)) {
```suggestion
  if ((event == Pinetime::Applications::TouchEvents::DoubleTap) && !lv_obj_get_hidden(btnClose)) {
```

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        uint32_t savedTick = 0;
This changes to FreeRTOS `TickType_t` also

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  void event_handler(lv_obj_t* obj, lv_event_t event) {
Should be `PascalCase`

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    savedTick = lv_tick_get();
Since #2264 we are now using `xTaskGetTickCount()` everywhere for consistency

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        char defaultBottomLabelColour[8] = "#ffffff";
Storing an `lv_color_t` for each would be more compact, but I haven't checked if it's possible to do it this way here. I think it should be though?

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  switch (prideFlagAsInt) {
It would be more readable here if you switched on the actual enum member instead, as then the names of each flag can be used in the case statements

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    case 0:
There's a lot of code duplication here between different flags. I'd prefer if it each flag had their key values stored in a data structure somewhere (number of sections, colour, text alignment, text colour) and then there could be one code path implementing the actual logic

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
Use something like `std::ranges::max` to automatically calculate the upper bound

2025-06-16 21:00 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        Utility::DirtyValue<bool> notificationState {};
These initialisers are redundant, as they are equivalent to the default initialiser

2025-06-16 21:12 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +#include "components/ble/BleController.h"
maaaaaybe. Do you mean in `static Screens::Screen* Create(AppControllers& controllers) {`? Otherwise they are not used in a function so I thought it should be alright. Maybe a learning opportunity for me here :sweat_smile:

2025-06-16 21:16 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
how would that look like? Wouldn't we need to explicitly list all enum values for that to work? or is it really just `std::ranges::max(Pinetime::Controllers::Settings::PrideFlag)`?

2025-06-16 21:16 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +#include "components/ble/BleController.h"
Looks like you're right that they can be removed here, but they will need to be moved into the .cpp file as their layout has to be known there

Also the BLE controller isn't stored as a reference or pointer, so that's an issue currently

2025-06-16 21:17 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
Yep that works I think, just need to static cast the result

2025-06-16 21:23 UTC, NeroBurner requested changes
suggestions to make the build work again

2025-06-16 21:23 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        const Controllers::Ble bleController;
this should be a reference

```suggestion
        const Controllers::Ble& bleController;
```

2025-06-16 21:23 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +#include "displayapp/Controllers.h"
we need the settingscontroller.h as `Controllers::Settings::PrideFlag` is used in the header file as value, so we can't forward declare it here. Just re-add the include for `SettingsController.h`

```suggestion
#include "components/settings/Settings.h"
#include "displayapp/Controllers.h"
```

2025-06-16 21:23 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +#include "displayapp/screens/Symbols.h"
includes removed from the header are missing

```suggestion
#include "components/battery/BatteryController.h"
#include "components/ble/BleController.h"
#include "displayapp/screens/Symbols.h"
```

2025-06-16 21:27 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +#include "components/ble/BleController.h"
code suggestions to fix those (and thus the build) in my latest review :)

2025-06-16 21:28 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
OK, while this is possible it requires a lot of metaprogramming currently. C++26 might change this

An alternative would be to add an END enum member, but that's kind of ugly and causes issues with that being a valid entry.

Since my suggestion looks to be (sensibly) unimplementable, I'm resolving this thread

2025-06-16 21:30 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
as far as I can see (or search for) we'd need `Boost.describe` or similar to make this work. C++20 alone doesn't seem to be enough
https://stackoverflow.com/questions/73679033/c20-range-from-enum

2025-06-16 21:32 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
https://taylorconor.com/blog/enum-reflection/ it does seem to be possible as the number of members in the enum is all we need to know. But it's not pretty :P

2025-06-16 21:35 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
let's wait for C++26 reflection instead :grin:

2025-06-16 21:43 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (prideFlagAsInt < 3) {
definitely :D

2025-06-17 13:14 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UseFlagData(PrideFlagData<N> flagData);
optional, but please explore if it is easily feasible:

this feels like it should be a private function :thinking: and even an implementation detail. Do you think you can completely move it into the `cpp` file? Maybe add a `WatchFacePrideFlag` reference parameter

2025-06-17 13:24 UTC, Aperture32GLaDOS commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UseFlagData(PrideFlagData<N> flagData);
I think the issue with moving it into the cpp file is that I'd have to either pass all the labels it changes individually as parameters, or make those labels public so I could access them from a WatchFacePrideFlag parameter.

I can definitely make it private, though (and I do agree, it should at least be private, if not a seperate function).

2025-06-17 13:25 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  notificationIcon = lv_label_create(lv_scr_act(), nullptr);
I haven't tested this on hardware and it's difficult to do with InfiniEmu, does the notification text look OK on all of the flags?

Also, maybe it'd be worth renaming this, as it's text now rather than an icon

2025-06-17 13:25 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UpdateScreen(Pinetime::Controllers::Settings::PrideFlag);
Should this be private?

2025-06-17 13:26 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UseFlagData(PrideFlagData<N> flagData);
then let's go for private for now and wait for @mark9064 to chime in on this one :)

2025-06-17 13:30 UTC, Aperture32GLaDOS commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  notificationIcon = lv_label_create(lv_scr_act(), nullptr);
Luckily enough, black has enough contrast on all the current flags to look good (or at least, they do on the emulator)
![image](https://github.com/user-attachments/assets/0729b7da-edce-43dd-87f0-22ee6bd46527)
![image](https://github.com/user-attachments/assets/bb149613-7370-49a1-a10f-474fea6b36f7)
![image](https://github.com/user-attachments/assets/0cc23f69-4280-4d32-9da2-46e279d08267)
![image](https://github.com/user-attachments/assets/260553a0-8f23-4789-86d7-78a04d9d8901)
Yeah, it should definitely be renamed though.

2025-06-17 13:33 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UseFlagData(PrideFlagData<N> flagData);
Private makes more sense to me as it mutates a lot of the watchface state :+1:

2025-06-17 13:38 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +            spacing = (uint8_t) (1.5f * ((float) N) + 40.5);
It would be better if this used C++ style casts rather than C style

Also, should it be 40.5f to avoid double promotion? Or maybe we use the cast all doubles to float compiler option, I don't remember

2025-06-17 13:42 UTC, Aperture32GLaDOS commented on src/displayapp/screens/WatchFacePrideFlag.h
> +            spacing = (uint8_t) (1.5f * ((float) N) + 40.5);
Yup, makes sense, I'll use 40.5f just to be sure

2025-06-17 13:57 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UpdateScreen(Pinetime::Controllers::Settings::PrideFlag);
Sorry I didn't make it clear, I was talking about the `UpdateScreen` method

2025-06-17 14:01 UTC, Aperture32GLaDOS commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        void UpdateScreen(Pinetime::Controllers::Settings::PrideFlag);
No worries, it's an easy fix anyhow

2025-06-17 14:21 UTC, Aperture32GLaDOS commented
Yeah, no worries - I'm flashing it now

2025-06-17 14:30 UTC, Aperture32GLaDOS commented
![wlw](https://github.com/user-attachments/assets/6b272428-1134-4773-8faa-a6b465b9aca9)
![bi](https://github.com/user-attachments/assets/57b9b0f9-479f-44cf-b734-ebfcedcfda31)
![mlm](https://github.com/user-attachments/assets/28e98099-815c-4ef6-9c93-9576a6bfdb92)
![trans](https://github.com/user-attachments/assets/96b87d90-79fa-4d5c-ac10-712302d7bf83)
The time is legible on all of them, but on the trans watch the day and date are invisible - if it's an issue we could change all text to be black

2025-06-17 14:41 UTC, mark9064 commented
I don't think it's a big issue - I'll leave whether white or black works better for the trans face to you :)

2025-06-17 14:46 UTC, Aperture32GLaDOS commented
In that case, I'd prefer to leave it as-is, with black for the time and white for everything else

2025-06-17 15:36 UTC, NeroBurner commented on src/components/settings/Settings.h
> +        PrideFlag prideFlag = PrideFlag::Gay;
non-blocking, probably I should create a new issue:

@mark9064 should we move watchface specific settings to their own settings files? like alarm does?

2025-06-17 15:48 UTC, mark9064 commented on src/components/settings/Settings.h
> +        PrideFlag prideFlag = PrideFlag::Gay;
That's a good point, they probably should. The main settings file should be for system settings only

But I also agree that it is its own issue, other watchface settings are in the main file so this can go there for now until we refactor later

2025-06-17 16:25 UTC, mark9064 commented on src/components/settings/Settings.h
> +        PrideFlag prideFlag = PrideFlag::Gay;
Issue created

2025-06-17 20:13 UTC, NeroBurner commented on src/components/datetime/DateTimeController.cpp
> +}
optional, no biggie, honestly I'd like to keep the function: this function is unused. But I'm not sure if the compiler is smart enough to remove it itself from the resulting binary :thinking: 
could you try if the size numbers change with and without this unused function?

2025-06-17 20:20 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        static Pinetime::Controllers::Settings::PrideFlag GetPrevious(Controllers::Settings::PrideFlag prideFlag);
those two functions could be moved completely into the `cpp` file into the private namespace

2025-06-17 20:24 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +            spacing = static_cast<uint8_t>(1.5f * static_cast<float>(N) + 40.5f);
even if it is just syntactic sugar, please use member initializers as we do for the `WatchFacePrideFlag` constructor (the member variables after the `:` symbol)

2025-06-17 20:39 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  Refresh();
CLion warning: Call to a virtual function inside a constructor is resolved at compile time

suggested fix: be explicit
```suggestion
  WatchFacePrideFlag::Refresh();
```

2025-06-17 20:43 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +void WatchFacePrideFlag::CloseMenu() {
optional: CLion suggests that `CloseMenu` member function can be made `const`
It doesn't feel like it should be `const` as we change the screen and hide some buttons

Thoughts?

2025-06-17 20:47 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  if (event == LV_EVENT_CLICKED) {
variables can be moved into the if, then we call `GetPrideFlag()` only if we need it
```suggestion
  if (event == LV_EVENT_CLICKED) {
    auto valueFlag = settingsController.GetPrideFlag();
    bool flagChanged = false;

```

2025-06-17 20:52 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.h
> +        uint8_t numBackgrounds;
unused, replaced by `PrideFlagData::N`
```suggestion
```

2025-06-17 20:53 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    uint8_t second = dateTimeController.Seconds();
clang-tidy: can be declared const

```suggestion
    uint8_t hour = dateTimeController.Hours();
    const uint8_t minute = dateTimeController.Minutes();
    const uint8_t second = dateTimeController.Seconds();
```

2025-06-17 20:55 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +      Controllers::DateTime::Days dayOfWeek = dateTimeController.DayOfWeek();
```suggestion
      const uint16_t year = dateTimeController.Year();
      const Controllers::DateTime::Months month = dateTimeController.Month();
      const uint8_t day = dateTimeController.Day();
      const Controllers::DateTime::Days dayOfWeek = dateTimeController.DayOfWeek();
```

2025-06-17 20:56 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    themeChanged = false;
we should use braces here, too many oopsies because of no braces and later just added one command and forgot to add the braces later
```suggestion
  if (themeChanged) {
    themeChanged = false;
  }
```

2025-06-17 21:00 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  auto prideFlagAsInt = static_cast<uint8_t>(prideFlag);
add const

```suggestion
  const auto prideFlagAsInt = static_cast<uint8_t>(prideFlag);
```

2025-06-17 21:00 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  auto prideFlagAsInt = static_cast<uint8_t>(prideFlag);
more const

```suggestion
  const auto prideFlagAsInt = static_cast<uint8_t>(prideFlag);
```

2025-06-17 21:04 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  for (uint8_t i = 0; i < N; i++) {
let's match the index variable with the type of the conditional `N`

```suggestion
  for (std::size_t i = 0; i < N; i++) {
```

2025-06-17 21:20 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +void WatchFacePrideFlag::UpdateScreen(Pinetime::Controllers::Settings::PrideFlag prideFlag) {
```suggestion
void WatchFacePrideFlag::UpdateScreen(const Pinetime::Controllers::Settings::PrideFlag prideFlag) {
```

2025-06-17 21:22 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +void WatchFacePrideFlag::UseFlagData(PrideFlagData<N> flagData) {
The function can be moved into the `UpdateScreen` function as a lambda with the following declaration:

```cpp
  auto UseFlagData = [this]<size_t N>(PrideFlagData<N> flagData) {
```

with this the `PrideFlagData` class can be moved from the header to `cpp` file as well

2025-06-17 21:37 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    WatchFacePrideFlag::PrideFlagData(gayColours, LV_COLOR_BLACK, LV_COLOR_BLACK, LV_COLOR_WHITE);
with the moved `PrideFlagData` class we can save a few typed redundant characters here. The `N` template parameter is taken from the `xxxColours` parameter

```suggestion
  constexpr PrideFlagData gayFlagData(gayColours, LV_COLOR_BLACK, LV_COLOR_BLACK, LV_COLOR_WHITE);
```

2025-06-17 23:28 UTC, mark9064 commented on src/components/datetime/DateTimeController.cpp
> +}
Linker stripping is on so this should be OK

2025-06-17 23:42 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  Refresh();
Note: this is not a functionality change but just highlights that the `Refresh()` from the base type (here `WatchFacePrideFlag`) will always be executed instead of `Refresh()`  from an inheriting type

Personally I don't think this change is needed as it breaks convention with every other app and watchface, but equally it's worth knowing why it's been suggested (I learnt something new today!!)

2025-06-17 23:43 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +    themeChanged = false;
Sidenote: this is fixed by #2139

2025-06-17 23:49 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +void WatchFacePrideFlag::CloseMenu() {
I think this shouldn't be const: the method mutates members even if the compiler doesn't see this as LVGL is a C library

2025-06-18 06:40 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +void WatchFacePrideFlag::CloseMenu() {
I agree, you've put into words what I vaguely thought :)

2025-06-18 06:41 UTC, NeroBurner commented on src/components/datetime/DateTimeController.cpp
> +}
TIL

2025-06-18 13:11 UTC, Aperture32GLaDOS commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +void WatchFacePrideFlag::UseFlagData(PrideFlagData<N> flagData) {
Damn, that's a clever usage of lambda functions!

2025-06-18 16:54 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +  constexpr PrideFlagData gayFlagData = PrideFlagData(gayColours, LV_COLOR_BLACK, LV_COLOR_BLACK, LV_COLOR_WHITE);
you can use the constructor directly here to save some typing work

```suggestion
  constexpr PrideFlagData gayFlagData(gayColours, LV_COLOR_BLACK, LV_COLOR_BLACK, LV_COLOR_WHITE);
```

2025-06-18 20:10 UTC, NeroBurner requested changes
just one last `const`, and then I think we're good to go!

It's been lovely working with you on this MR @Aperture32GLaDOS

2025-06-18 20:10 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +                            lv_color_t defaultBottomLabelColour)
more const I've overlooked until now

```suggestion
                            const lv_color_t defaultTopLabelColour,
                            const lv_color_t labelTimeColour,
                            const lv_color_t defaultBottomLabelColour)
```

2025-06-18 20:29 UTC, mark9064 commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +                            lv_color_t defaultBottomLabelColour)
I have to admit, I think you've gone a little overboard with consting :P my opinion aligns quite well with this blog https://quuxplusone.github.io/blog/2022/01/23/dont-const-all-the-things

Admittedly I much prefer the default immutability of rust

2025-06-18 21:12 UTC, NeroBurner commented on src/displayapp/screens/WatchFacePrideFlag.cpp
> +                            lv_color_t defaultBottomLabelColour)
he brings up very good reasoning. I just followed along with the CLion suggestions as I thought those are best practice. Marking as resolved

2025-06-18 21:15 UTC, NeroBurner approved these changes
all looking good. Thanks for the contribution and your great teamwork! I had fun reviewing and learning on this PR

2025-06-19 10:21 UTC, Aperture32GLaDOS commented
Brilliant! Thanks all for the advice and feedback, it's been very helpful

2025-06-19 16:53 UTC, merged