Ticker
InfiniTimeOrg/InfiniTime pull request #510
Opened 2021-07-22 03:01 UTC by wilsonjwco

Feature add. Added a scrolling ticker on the digital watch face. Ticker has 3 modes controlled by a settings screen.

1. Off: Do not display the ticker.
2. Update: Display the most recent message. As a convenience, the last message can be seen at a glance without the need to swipe up.
3. Keep: Keep the currently displayed message, and do not update it when receiving new messages. Useful for persistent reminders or to help with learning/memorizing facts, Bible verses, quotes, etc. Message can be set manually using GadgetBridge's Debug screen.

Compiled, downloaded OTA to my watch, and tested. 

Pics can be seen on this google shared album: [https://photos.app.goo.gl/HSDs2YWnEf5c1Xk48](https://photos.app.goo.gl/HSDs2YWnEf5c1Xk48)

Ideas for future functionality:

- display news/RSS items
- stock market ticker
- user-programmable filter to show only high priority or certain types of messages on the watch face
- display status from other apps (notify when timer is done, or when step goal met)
- debug/log messages for developers trying to catch rare or hard to repeat bugs

2021-07-22 08:40 UTC, Avamander requested changes

2021-07-22 08:40 UTC, Avamander commented on src/components/settings/Settings.h
> +        if (ticker != settings.tickerMode)
Missing braces

2021-07-22 08:40 UTC, Avamander commented on src/displayapp/screens/WatchFaceDigital.cpp
> +  }
Unnecessary comment

2021-07-22 08:40 UTC, Avamander commented on src/displayapp/screens/WatchFaceDigital.cpp
> +    } else
Missing brace

2021-07-22 08:40 UTC, Avamander commented on src/displayapp/screens/WatchFaceDigital.h
> +	lv_obj_t* label_ticker;
Run clang-format on these files.

2021-07-22 08:40 UTC, Avamander commented on src/displayapp/screens/settings/SettingTicker.cpp
> +        };
Unnecessary semicolons

2021-07-22 09:06 UTC, Riksu9000 commented
Maybe instead of having modes, we could simply pin a notification to show on the watchface.

2021-07-22 12:20 UTC, 0x1a8510f2 commented
Just so you're aware @wilsonjwco, you haven't removed geolocation data from the photos in the album, meaning that anyone can see where the photo was taken (likely where you live). Would recommend you delete the album and re-create it without geolocation data (there should be a setting in Google photos).

2021-07-22 14:42 UTC, wilsonjwco commented
> Maybe instead of having modes, we could simply pin a notification to show on the watchface.

Do you mean we could have a button on the watch face that would pin the current notification?

2021-07-22 14:44 UTC, wilsonjwco commented
Thanks everyone for the comments, I'll work through them. Also noticed the message get corrupted after a few wake cycles, so it looks like I've got more debugging to do before it's merged.

2021-07-22 15:11 UTC, Riksu9000 commented
> > Maybe instead of having modes, we could simply pin a notification to show on the watchface.
> 
> @Riksu9000 do you mean we could have a button on the watch face that would pin the current notification?

No. I was thinking something like opening the notification that we want to pin and long pressing on it. Then when we return to the watch face, it would be shown there. This way we could easily choose any notification to keep.

2021-07-22 19:42 UTC, wilsonjwco commented
> I was thinking something like opening the notification that we want to pin and long pressing on it.

Great idea-- I'll get rid of the settings and make it like you suggested. Will follow up with this discussion once I've done this, fixed the above mentioned problems, and am ready for the merge to be considered again.

2021-10-04 19:30 UTC, lman0 commented
any new on this @wilsonjwco ?

2022-02-14 15:35 UTC, Riksu9000 commented
I'll close this since it's very outdated. Please create a new PR if you want to keep working on the notification pinning feature.

2022-02-14 15:35 UTC, closed without merging