Add post_build.sh
InfiniTimeOrg/InfiniTime pull request #574
Opened 2021-08-12 15:39 UTC by MysteriousLog6

Add post_build.sh to .gitignore

2021-08-14 19:14 UTC, JF002 commented
I might be wrong, but I don't think this is needed:  `post_build.sh` is generated by cmake in the build folder, which should not be tracked by git.
In which situation did you notice that git would add this file?

2021-08-14 19:57 UTC, Avamander commented
> In which situation did you notice that git would add this file?

When you don't follow best-practice and run `cmake` in the project's root folder (instead of `build`). It doesn't get instantly added, but people have accidentally added it to git themselves.

2021-10-03 14:35 UTC, Avamander requested changes
This doesn't hurt and can avoid someone accidentally adding these files, even if they aren't running `cmake` in the right folder. If that one line is reverted it's fine to merge.

2021-10-03 14:35 UTC, Avamander commented on src/main.cpp
> -
This change is not needed

2022-04-25 13:10 UTC, Avamander commented
I'll close this as it's a counter to cmake misuse, which might have future unintended consequences we don't want to deal with.

2022-04-25 13:10 UTC, closed without merging