Added Trip meter to Steps app
InfiniTimeOrg/InfiniTime pull request #764
Opened 2021-10-20 05:16 UTC by stephanie-eng

Fixes #694 

- Added a lap button (similar to the lap button in Stopwatch) to reset the step counter.
- Added a total step count in that does not get reset in the bottom right corner.
- Moved/shrank existing Steps UI to fit the new button and total step count
- Added a variable to MotionController to save the steps since the last lap.

Note that using the lap button does not reset the progress to the daily step goal. The progress bar uses the total step count.

The image below demos the new button after fresh boot with (1) 0 steps, (2) the watch after taking some steps (step count and total updated and equal), (3) pressing the lap button (step count reset, no change to total), and (4) after walking again (step count and total updated, but not equal).

![image](https://user-images.githubusercontent.com/10466537/138031131-6ff4be85-5b27-4284-9c45-7e97d2e705cd.png)

I also checked that large step counts do not cause display issues.

![image](https://user-images.githubusercontent.com/10466537/138032311-0af0a4a9-bc5e-461a-a91d-96c0d40c7b5f.png)

2021-10-20 19:22 UTC, stephanie-eng commented
Thanks for your input. I've changed the lap button to a trip reset button and made the UI changes. The below image shows the new behaviour:

1. The watch after fresh boot, no steps taken. Steps and trip meter are both 0.
2. The watch after taking 36 steps, trip meter matches step count
3. Pressing the reset button resets the trip meter to 0, without changing the step count. Progress bar for step goal also remains unchanged.
4. Setting the time to before midnight to reset the daily step count
5. Step count in the UI is shown to be 0
6. Step count after midnight in the step app: step count reset to 0, but trip meter remains unchanged from 36. Progress bar for step goal is reset to 0.
7. Taking an additional 20 steps increments step count to 20, and trip meter to 56 (36 steps from yesterday + 20 from the new day)
8. Trip meter can be set back to 0 with the reset button

![image](https://user-images.githubusercontent.com/10466537/138157316-371facca-6227-4136-b39e-6a856b4d0423.png)

2021-10-22 03:42 UTC, stephanie-eng commented
Good point - thanks for the catch. I've changed the trip meter to update with the steps rather than from the app. I also found a bug in my logic for detecting new days and fixed that as well.

2021-10-31 10:42 UTC, Avamander requested changes

2021-10-31 10:42 UTC, Avamander commented on src/components/motion/MotionController.cpp
> +  if(deltaSteps > 0){
Requires formatting with clang-format.

2021-10-31 10:42 UTC, Avamander commented on src/components/motion/MotionController.h
> +      uint32_t GetTripSteps() const {
Requires formatting with clang-format.

2021-10-31 15:58 UTC, Avamander approved these changes
Looks good style and format-wise. Needs testing on a physical device.

2021-10-31 16:04 UTC, stephanie-eng commented
To produce the above screenshots, I did test the code with a physical device. If anyone else would like to try it as another point of data, that could be good.

As an aside, clang-format didn't initially work with VSCode in the container out of the box for me - I had to tweak some settings to get it to use the right executable and format on save. I can create a separate issue to document this.

2021-12-30 20:51 UTC, JF002 commented
@stephanie-eng Thank you for this nice first PR! It's very well documented with test cases and pictures! I would be happy if we received more PR like this one as it makes the review much easier!

2021-12-30 20:51 UTC, merged