InfiniPaint vibrate on colorchange, fix color rotation
InfiniTimeOrg/InfiniTime pull request #803
Opened 2021-10-31 20:38 UTC by clemensvonmolo

This is a very simple pull requests that changes the Paint app in order to vibrate on color change (because It's hard to know if the touch controller actually registered a long press or a small swipe). I also fixed the logic for the color rotation. Before, the color magenta was unreachable and instead black was chosen a second time. The `color`  variable was changed to initialize to 3 instead of 2, so you don't have to press twice on the first rotation.

- [x] the changes were successfully tested on hardware and showed no problems.

2021-10-31 23:04 UTC, 0x1a8510f2 commented
Whoa, didn't even realise the colours could be changed!

2021-11-01 04:01 UTC, geekbozu commented
Not super related to this PR but I would love to see a way to just set a system event for the motor instead of having to pass this around so much....Nice pr tho didn't know you could change the color.

2021-11-01 08:53 UTC, Riksu9000 requested changes
A proper fix for the color would be to increment the color before the switch and modulo with 8. That way we use 0-7 instead of 1-8. Currently the color variable points to the next color instead of the current one which is strange.

The vibration is a good idea.

2021-11-01 08:53 UTC, Riksu9000 commented on src/displayapp/screens/InfiniPaint.cpp
> +InfiniPaint::InfiniPaint(Pinetime::Applications::DisplayApp* app, Pinetime::Components::LittleVgl& lvgl, Pinetime::Controllers::MotorController& motor) : Screen(app), lvgl {lvgl}, motor{motor} {
This line is too long now. Use clang-format to break it up.

2021-11-01 08:53 UTC, Riksu9000 commented on src/displayapp/DisplayApp.cpp
> +      currentScreen = std::make_unique<Screens::InfiniPaint>(this, lvgl,motorController);
Reformat with clang-format.

2021-11-01 11:00 UTC, Riksu9000 reviewed
Maybe the vibration doesn't have to be so strong. 35 duration is usually used elsewhere.

Other than that this looks good.

2021-11-01 11:09 UTC, clemensvonmolo commented
The run duration seems a bit all over the place. (Currently 50, 90, 30, 35 and 15 are used.) Maybe a design guideline with times for strong/medium/weak vibration would help. For now I will change it to 35 since that really is the most common one.

2021-11-01 11:13 UTC, Riksu9000 approved these changes

2021-11-01 14:51 UTC, geekbozu approved these changes

2021-12-02 20:43 UTC, merged